name: 'GitHub Actions Weather Bot'
on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *
  watch:
    types: started

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Weather'
        run: bash ./weather.sh ${{ secrets.CITY_NAME }}
      - name: 'Get Date'
        run: echo "::set-env name=REPORT_DATE::$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"
      - name: 'Send mail'
        uses: huhublog/action-send-mail@master
        with:
          server_address: hwhzsmtp.qiye.163.com
          server_port: 994
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Hi, Weather Report Coming!
          body: file://result.html
          to: ${{ secrets.TARGET_EMAIL }}
          from: huhuhub.github.io
          content_type: text/html
